In [2]:
#Ejercicios:
#1) importar numpy
#2) crear array con la siguiente estructura

# [[1,  6, 11],
# [2,  7, 12],
# [3,  8, 13],
# [4,  9, 14],
# [5, 10, 15]]
#de nombre array

#3) revisar forma del array
#4) selecciona la segunda columna
#5) crea un vector con los valores del 15 al 55, de nombre array2
#6) asigna el valor 23 a la quinta posicion del array2
#7) convierte el array2 al reves
#8) crear matriz diagonal donde los elementos de la diagonal sean 5 primeros valores pares de array2, llamala matriz_diag pista:
#usar np.diag
#9) imprimir el numero de dimensiones de la matriz diagonal
#10) crea matriz con numeros aleatorios de tamaño 5x3 de nombre matriz
#11) multiplica matriz por matriz_diag

In [3]:
#1) importar numpy
import numpy as np

In [4]:
#2) crear array con la siguiente estructura

# [[1,  6, 11],
# [2,  7, 12],
# [3,  8, 13],
# [4,  9, 14],
# [5, 10, 15]]
#de nombre array

array = np.array([
    [1,6,11],
    [2,7,12],
    [3,8,13],
    [4,9,14],
    [5,10,15]
])
array

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [5]:
#3) revisar la forma del array.
array.shape

(5, 3)

In [8]:
#4) seleccionar la segunda columna
array[:,1]

array([ 6,  7,  8,  9, 10])

In [14]:
#5) crear un vector con los valores del 15 al 55 de nombre array2
array2 = np.array(np.arange(15,56))
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [15]:
#6) asigna el valor 23 a la quinta posicion del array2
array2[4] = 23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [30]:
#7) convierte el array2 al reves
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

In [47]:
#8) crear matriz diagonal donde los elementos de la diagonal sean 5 primeros valores pares de array2, llamala matriz_diag pista:
#usar np.diag

np.diag(array2[1::2][:5])

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

In [48]:
matriz_diag = np.diag(array2[1::2][:5])
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

In [50]:
#9) imprimir numero de dimensiones de la matriz diagonal
matriz_diag.ndim

2

In [51]:
#10) crea matriz con numeros aleatorios de tamaño 5x3 de nombre matriz

matriz = np.random.rand(5,3)
matriz

array([[0.44160927, 0.54828039, 0.97809367],
       [0.59312292, 0.05941313, 0.02098319],
       [0.47629322, 0.11371056, 0.72687696],
       [0.42027205, 0.55459807, 0.04582146],
       [0.31271207, 0.05572741, 0.86900013]])

In [53]:
#11) multiplica matriz por matriz_diag
matriz.dot(matriz_diag)

ValueError: shapes (5,3) and (5,5) not aligned: 3 (dim 1) != 5 (dim 0)

In [54]:
#para resolver lo anterior con "Transponer"
matriz.T.shape

(3, 5)

In [55]:
matriz.T @ matriz_diag

array([[ 7.06574836, 10.67621248,  9.52586433,  9.24598503,  7.50508961],
       [ 8.77248625,  1.0694363 ,  2.27421116, 12.20115745,  1.33745786],
       [15.64949876,  0.37769743, 14.53753916,  1.00807215, 20.85600321]])