In [1]:
import sys
!{sys.executable} -m pip install numpy

In [2]:
import numpy as np
array_1d = np.array([4.5, 3])
type(array_1d)

numpy.ndarray

In [3]:
#como hacer una matriz (lista de dos dimensiones o lista de listas...)
matriz = np.array([
    [1,2,3],
    [4,5,6]
])
matriz.ndim


2

In [4]:
matriz.shape

(2, 3)

In [5]:
#crear array/matriz de 0 ceros
matriz_de_ceros = np.zeros((3,2))
print(matriz_de_ceros)
#crear array/matriz de unos
array_de_unos = np.ones((2))
print(array_de_unos)
#crear array/matriz de identidad
matriz_de_identidad = np.eye(3)
print(matriz_de_identidad)
#crear array de numeros random, y 2 filas 3 columnas
matriz_random = np.random.random((2,3))
print(matriz_random)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.65294053 0.49048463 0.42789683]
 [0.44073771 0.10033809 0.4796052 ]]


In [6]:
!cat np_text.text

"cat" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [8]:
np_text = np.genfromtxt("np_text.txt", delimiter = ',')
np_text

ValueError: Some errors were detected !
    Line #4 (got 3 columns instead of 4)

In [9]:
np_text = np.genfromtxt("np_text.txt", delimiter = ',')
np_text

ValueError: Some errors were detected !
    Line #4 (got 3 columns instead of 4)

In [10]:
np_text = np.genfromtxt("np_text.txt", delimiter = ',')
np_text

array([ 1.,  2.,  3., 43., 87., 94.,  6., 89., 56., 74.,  8.,  2.])

In [13]:
#medir tamaño de la variable (y diferencia entre lista comun y array numpy)
lista_grande = list(range(100000))
array_grande_np = np.array(range(100000))

In [14]:
sys.getsizeof(lista_grande)

800056

In [15]:
sys.getsizeof(array_grande_np)

400104

In [17]:
%%timeit
#medir tiempo de una ejecucion
sum(range(10000000))

334 ms ± 2.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
%%timeit
#la ejecucion de numpy es mas rapida
np.sum(np.arange(10000000))

15.7 ms ± 182 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
#ver tipo de datos de los elementos
np.array([1.2,2.3,3.0,4.6,5.9]).dtype

dtype('float64')

In [20]:
#para asignar un tipo de dato especifico se usa dtype = int (o el tipo de dato que se necesita)
np.array([1.2,2.3,3.0,4.6,5.9], dtype=int).dtype

dtype('int32')

In [21]:
%%timeit
["{}".format(i) for i in range(100000)]

24.6 ms ± 358 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
f = np.vectorize(lambda x: "{}".format(x))

In [23]:
%%timeit
f(np.arange(100000))

44.7 ms ± 2.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
#formas de mostrar datos de un array. Matriz de 3 filas 4 columnas.
matriz_34 = np.array([
    [1,2,3,4],[5,6,7,8],[9,10,11,12]
])

matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
#ver filas y/o columnas: matriz[n] donde n es el numero de fila
matriz_34[0]

array([1, 2, 3, 4])

In [27]:
#primeros elementos matriz[:n] donde : es "todas las filas" n es la cantidad de filas a mostrar
matriz_34[:2] #dos primeros filas

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
matriz_34[0][1]

2

In [29]:
matriz_34[0,1]

2

In [31]:
#ver una columna: matriz[:,k] donde k es el numero de elemento(columna). Los : es "dame todas las filas" y k "dame k columna"
matriz_34[:,2] #todas las filas de la segunda columna

array([ 3,  7, 11])

In [34]:
#evaluar condiciones en una matriz
matriz_32 = np.array([[1,4],[2,4],[5,0]])
matriz_32

array([[1, 4],
       [2, 4],
       [5, 0]])

In [38]:
#se puede evaluar una condicion de la matriz, por ejemplo si los numeros son mayores o menores, si pertenece al array, etc.
#se devuelve un array booleano (True/False)
#Ejemplo
indice_filtrado = matriz_32 >= 2
indice_filtrado

array([[False,  True],
       [ True,  True],
       [ True, False]])

In [39]:
matriz_32[indice_filtrado]

array([4, 2, 4, 5])

In [40]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[23,5],[3,0]])

In [41]:
#operaciones con arrays
#sumar
array1+array2
#multiplicar
array1*array2
#multiplicacion matricial python 3.5+
array1 @ array2
#con array1.dot(array2) se hace en python menor a 3.5

array([[29,  5],
       [81, 15]])